import "./globals.css";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Next 13</title>
      </head>
      <body>
        <div className={styles.header}>From layout</div>
        {children}
      </body>
    </html>
  );
}
